[package]
name = "status_bar"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
expanduser = "1.2.2"
font-loader = "0.11.0"
hyprland = "0.4.0-beta.2"
serde = "1.0.219"
serde_json = "1.0.140"
sysinfo = "0.34.2"
widgets = { git = "https://github.com/Elkan10/wl_widgets_lib.git"}
